apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.serviceName }}-env-vars"
data:
  MCMA_LOGGER_SOURCE: {{ .Values.serviceName | quote }}
  MCMA_PUBLIC_URL: "http://{{ .Values.serviceName }}/mcma/api"
  MCMA_SERVICES_URL: "http://{{ .Values.serviceName }}/mcma/api/services"
  MCMA_MONGODB_CONNECTION_STRING: {{ .Values.mongoDb.connectionString | quote }}
  MCMA_MONGODB_DATABASE_NAME: {{ .Values.mongoDb.databaseName | quote }}
  MCMA_MONGODB_COLLECTION_NAME: {{ .Values.mongoDb.collectionName | quote }}